<?php 
$test=$block->getArticles();
?><table border=2 >
 <tr>
    <th>EmployeeID</th>
    <th> First Name</th>
    <th>Last Name</th>
    <th> Email</th>
    <th> CompanyName</th>
    <th> Department</th>
    <th> Occupation</th>
    <th> MobileNumber</th>
    <th>Address</th>
    <th> Joining Date</th>
    <th>Birthday</th>

</tr>

<?php
foreach($test as $data):
?>
<tr>
<td><?php echo $data->getemp_id(); ?></td>
<td><?php echo $data->getemp_fname(); ?></td>
<td><?php echo $data->getemp_lname(); ?></td>
<td><?php echo $data->getemail(); ?></td>
<td><?php echo $data->getcmpny_name(); ?></td>
<td><?php echo $data->getdept_name(); ?></td>
<td><?php echo $data->getoccupation(); ?></td>
<td><?php echo $data->getmob_no(); ?></td>
<td><?php echo $data->getaddress(); ?></td>
<td><?php echo $data->getjoindate(); ?></td>
<td><?php echo $data->getdob(); ?></td>
</tr>

<?php endforeach; ?>
</table>
